-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "initialOdometerKm" INTEGER;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "currentOdometerKm" INTEGER;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "lastServiceOdometerKm" INTEGER;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "serviceIntervalKm" INTEGER NOT NULL DEFAULT 10000;
